// Fotos reales del local para las categorías que ya las tienen (resto sigue con icon_url o el numero/placeholder).
export const CATEGORY_PHOTOS: Record<string, string> = {
  gastronomia: '/images/categoria-gastronomia.webp',
  almacen: '/images/categoria-almacen.jpg',
  almacenamiento: '/images/categoria-almacenamiento.webp',
  frio: '/images/categoria-frio.webp',
  hogar: '/images/categoria-hogar.webp',
  decoracion: '/images/categoria-decoracion.webp',
  herramientas: '/images/categoria-herramientas.webp',
  carniceria: '/images/categoria-carniceria.webp',
  climatizacion: '/images/categoria-climatizacion.webp',
  'deportes-aire-libre': '/images/categoria-deportes-aire-libre.webp',
  electronica: '/images/categoria-electronica.webp',
  estetica: '/images/categoria-estetica.webp',
  motos: '/images/categoria-motos.webp',
  muebles: '/images/categoria-muebles.webp',
  oficina: '/images/categoria-oficina.webp',
  panaderia: '/images/categoria-panaderia.webp',
  'peluqueria-barberia': '/images/categoria-peluqueria-barberia.webp',
};
