-- Migracion 043: agrega el placement 'financiacion' a la tabla promotions
-- y carga las 69 imagenes de promos con precios (carpeta CATALOGO PROMOS,
-- subcarpetas JUNIO y MARKET) para la nueva seccion "Equipa tu negocio con
-- estas promos en financiacion" de la home. Promos vigentes de julio, hasta
-- agotar stock. Administrables desde /admin/promociones (placement
-- "Promos en financiacion").

alter table promotions drop constraint if exists promotions_placement_check;
alter table promotions add constraint promotions_placement_check
  check (placement in ('hero','banner','strip','financiacion'));

insert into promotions (title, image_url, cta_link, placement, sort_order, active) values
  ('Promo financiación julio — Junio 2', '/images/promos-financiacion/junio/2.png', '/financiacion', 'financiacion', 1, true),
  ('Promo financiación julio — Junio 3', '/images/promos-financiacion/junio/3.png', '/financiacion', 'financiacion', 2, true),
  ('Promo financiación julio — Junio 4', '/images/promos-financiacion/junio/4.png', '/financiacion', 'financiacion', 3, true),
  ('Promo financiación julio — Junio 5', '/images/promos-financiacion/junio/5.png', '/financiacion', 'financiacion', 4, true),
  ('Promo financiación julio — Junio 6', '/images/promos-financiacion/junio/6.png', '/financiacion', 'financiacion', 5, true),
  ('Promo financiación julio — Junio 7', '/images/promos-financiacion/junio/7.png', '/financiacion', 'financiacion', 6, true),
  ('Promo financiación julio — Junio 8', '/images/promos-financiacion/junio/8.png', '/financiacion', 'financiacion', 7, true),
  ('Promo financiación julio — Junio 9', '/images/promos-financiacion/junio/9.png', '/financiacion', 'financiacion', 8, true),
  ('Promo financiación julio — Junio 10', '/images/promos-financiacion/junio/10.png', '/financiacion', 'financiacion', 9, true),
  ('Promo financiación julio — Junio 11', '/images/promos-financiacion/junio/11.png', '/financiacion', 'financiacion', 10, true),
  ('Promo financiación julio — Junio 12', '/images/promos-financiacion/junio/12.png', '/financiacion', 'financiacion', 11, true),
  ('Promo financiación julio — Junio 13', '/images/promos-financiacion/junio/13.png', '/financiacion', 'financiacion', 12, true),
  ('Promo financiación julio — Junio 14', '/images/promos-financiacion/junio/14.png', '/financiacion', 'financiacion', 13, true),
  ('Promo financiación julio — Junio 15', '/images/promos-financiacion/junio/15.png', '/financiacion', 'financiacion', 14, true),
  ('Promo financiación julio — Junio 16', '/images/promos-financiacion/junio/16.png', '/financiacion', 'financiacion', 15, true),
  ('Promo financiación julio — Junio 17', '/images/promos-financiacion/junio/17.png', '/financiacion', 'financiacion', 16, true),
  ('Promo financiación julio — Junio 18', '/images/promos-financiacion/junio/18.png', '/financiacion', 'financiacion', 17, true),
  ('Promo financiación julio — Junio 19', '/images/promos-financiacion/junio/19.png', '/financiacion', 'financiacion', 18, true),
  ('Promo financiación julio — Junio 20', '/images/promos-financiacion/junio/20.png', '/financiacion', 'financiacion', 19, true),
  ('Promo financiación julio — Junio 21', '/images/promos-financiacion/junio/21.png', '/financiacion', 'financiacion', 20, true),
  ('Promo financiación julio — Junio 22', '/images/promos-financiacion/junio/22.png', '/financiacion', 'financiacion', 21, true),
  ('Promo financiación julio — Junio 23', '/images/promos-financiacion/junio/23.png', '/financiacion', 'financiacion', 22, true),
  ('Promo financiación julio — Junio 24', '/images/promos-financiacion/junio/24.png', '/financiacion', 'financiacion', 23, true),
  ('Promo financiación julio — Junio 25', '/images/promos-financiacion/junio/25.png', '/financiacion', 'financiacion', 24, true),
  ('Promo financiación julio — Junio 26', '/images/promos-financiacion/junio/26.png', '/financiacion', 'financiacion', 25, true),
  ('Promo financiación julio — Junio 27', '/images/promos-financiacion/junio/27.png', '/financiacion', 'financiacion', 26, true),
  ('Promo financiación julio — Junio 28', '/images/promos-financiacion/junio/28.png', '/financiacion', 'financiacion', 27, true),
  ('Promo financiación julio — Junio 29', '/images/promos-financiacion/junio/29.png', '/financiacion', 'financiacion', 28, true),
  ('Promo financiación julio — Junio 31', '/images/promos-financiacion/junio/31.png', '/financiacion', 'financiacion', 29, true),
  ('Promo financiación julio — Junio 32', '/images/promos-financiacion/junio/32.png', '/financiacion', 'financiacion', 30, true),
  ('Promo financiación julio — Junio 33', '/images/promos-financiacion/junio/33.png', '/financiacion', 'financiacion', 31, true),
  ('Promo financiación julio — Junio 34', '/images/promos-financiacion/junio/34.png', '/financiacion', 'financiacion', 32, true),
  ('Promo financiación julio — Junio 35', '/images/promos-financiacion/junio/35.png', '/financiacion', 'financiacion', 33, true),
  ('Promo financiación julio — Junio 36', '/images/promos-financiacion/junio/36.png', '/financiacion', 'financiacion', 34, true),
  ('Promo financiación julio — Junio 37', '/images/promos-financiacion/junio/37.png', '/financiacion', 'financiacion', 35, true),
  ('Promo financiación julio — Junio 38', '/images/promos-financiacion/junio/38.png', '/financiacion', 'financiacion', 36, true),
  ('Promo financiación julio — Junio 39', '/images/promos-financiacion/junio/39.png', '/financiacion', 'financiacion', 37, true),
  ('Promo financiación julio — Junio 40', '/images/promos-financiacion/junio/40.png', '/financiacion', 'financiacion', 38, true),
  ('Promo financiación julio — Junio 41', '/images/promos-financiacion/junio/41.png', '/financiacion', 'financiacion', 39, true),
  ('Promo financiación julio — Junio 42', '/images/promos-financiacion/junio/42.png', '/financiacion', 'financiacion', 40, true),
  ('Promo financiación julio — Junio 43', '/images/promos-financiacion/junio/43.png', '/financiacion', 'financiacion', 41, true),
  ('Promo financiación julio — Junio 44', '/images/promos-financiacion/junio/44.png', '/financiacion', 'financiacion', 42, true),
  ('Promo financiación julio — Market 1', '/images/promos-financiacion/market/1.png', '/financiacion', 'financiacion', 43, true),
  ('Promo financiación julio — Market 2', '/images/promos-financiacion/market/2.png', '/financiacion', 'financiacion', 44, true),
  ('Promo financiación julio — Market 3', '/images/promos-financiacion/market/3.png', '/financiacion', 'financiacion', 45, true),
  ('Promo financiación julio — Market 4', '/images/promos-financiacion/market/4.png', '/financiacion', 'financiacion', 46, true),
  ('Promo financiación julio — Market 5', '/images/promos-financiacion/market/5.png', '/financiacion', 'financiacion', 47, true),
  ('Promo financiación julio — Market 6', '/images/promos-financiacion/market/6.png', '/financiacion', 'financiacion', 48, true),
  ('Promo financiación julio — Market 7', '/images/promos-financiacion/market/7.png', '/financiacion', 'financiacion', 49, true),
  ('Promo financiación julio — Market 8', '/images/promos-financiacion/market/8.png', '/financiacion', 'financiacion', 50, true),
  ('Promo financiación julio — Market 9', '/images/promos-financiacion/market/9.png', '/financiacion', 'financiacion', 51, true),
  ('Promo financiación julio — Market 10', '/images/promos-financiacion/market/10.png', '/financiacion', 'financiacion', 52, true),
  ('Promo financiación julio — Market 11', '/images/promos-financiacion/market/11.png', '/financiacion', 'financiacion', 53, true),
  ('Promo financiación julio — Market 12', '/images/promos-financiacion/market/12.png', '/financiacion', 'financiacion', 54, true),
  ('Promo financiación julio — Market 13', '/images/promos-financiacion/market/13.png', '/financiacion', 'financiacion', 55, true),
  ('Promo financiación julio — Market 14', '/images/promos-financiacion/market/14.png', '/financiacion', 'financiacion', 56, true),
  ('Promo financiación julio — Market 15', '/images/promos-financiacion/market/15.png', '/financiacion', 'financiacion', 57, true),
  ('Promo financiación julio — Market 16', '/images/promos-financiacion/market/16.png', '/financiacion', 'financiacion', 58, true),
  ('Promo financiación julio — Market 17', '/images/promos-financiacion/market/17.png', '/financiacion', 'financiacion', 59, true),
  ('Promo financiación julio — Market 18', '/images/promos-financiacion/market/18.png', '/financiacion', 'financiacion', 60, true),
  ('Promo financiación julio — Market 19', '/images/promos-financiacion/market/19.png', '/financiacion', 'financiacion', 61, true),
  ('Promo financiación julio — Market 20', '/images/promos-financiacion/market/20.png', '/financiacion', 'financiacion', 62, true),
  ('Promo financiación julio — Market 21', '/images/promos-financiacion/market/21.png', '/financiacion', 'financiacion', 63, true),
  ('Promo financiación julio — Market 22', '/images/promos-financiacion/market/22.png', '/financiacion', 'financiacion', 64, true),
  ('Promo financiación julio — Market 23', '/images/promos-financiacion/market/23.png', '/financiacion', 'financiacion', 65, true),
  ('Promo financiación julio — Market 24', '/images/promos-financiacion/market/24.png', '/financiacion', 'financiacion', 66, true),
  ('Promo financiación julio — Market 25', '/images/promos-financiacion/market/25.png', '/financiacion', 'financiacion', 67, true),
  ('Promo financiación julio — Market 26', '/images/promos-financiacion/market/26.png', '/financiacion', 'financiacion', 68, true),
  ('Promo financiación julio — Market 27', '/images/promos-financiacion/market/27.png', '/financiacion', 'financiacion', 69, true);
