-- Migracion 078: resuelve el resto del cluster de Kits Kemei usando el
-- campo "Modelo" de los specs de cada publicacion de ML (mas confiable
-- que el titulo libre, que a veces tiene typos como se detecto en la
-- correccion previa de LFJ-KM-291 -> LFJ-KM-2299). Ya aplicado.

-- LFJTXD-KM-8559 "Kit clipper + trimmer + shaver inalambrico - Lubricante, cepillo de limpieza, base carga y baterias (x2)" <- MLA1711712733 "Kit Clipper + Trimmer + Shaver Con Cuchillas De Acero Kemei Azul"
-- Tercera publicacion de ML para KM-8559 (confirmado por campo Modelo de los specs), ya tiene datos de fusiones anteriores
update products set active = false, ml_item_id = null where sku = 'MLA1711712733';

-- LFJ-KM-1784 "Trimmer inalambrico - 3 posiciones - 1 a 3  mm - Lubricante, cepillo de limpieza" <- MLA1714142711 "Patillera Trimmer Inalámbrica + Accesorios 7000rpm Kemei Dorado Oscuro" + MLA3081809124 "Patillera Trimmer Inalámbrica + Accesorios 6500rpm Kemei Gris"
-- Modelo KM-1784 confirmado en specs de ambas publicaciones; las dos con stock exacto (60)
update products set
  images = '["https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA1714142711-1.webp","https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA1714142711-2.webp","https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA1714142711-3.jpg","https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA1714142711-4.jpg","https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA1714142711-5.jpg","https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA1714142711-6.jpg"]'::jsonb,
  specs = '[{"label":"Accesorios incluidos","value":"Cargador,Cuchillas de acero,Peines guía"},{"label":"Voltaje de la batería","value":"220V"},{"label":"Marca","value":"Kemei"},{"label":"Color","value":"Dorado oscuro"},{"label":"Funciones","value":"Cortadora de pelo,Afeitadora"},{"label":"Tipos de cabezales","value":"Ergónomicos,Removibles"},{"label":"Incluye accesorios","value":"Sí"},{"label":"Incluye batería recargable","value":"Sí"},{"label":"Es apta para bebés","value":"Sí"},{"label":"Es apta para viaje","value":"Sí"},{"label":"Es inalámbrica","value":"Sí"},{"label":"Condición del ítem","value":"Nuevo"},{"label":"Modelo","value":"KM-1784"},{"label":"Tipo de alimentación","value":"Batería recargable"},{"label":"Voltaje","value":"220V"},{"label":"Con cabezales lavables","value":"Sí"}]'::jsonb,
  description = 'La Patillera Trimmer Inalámbrica Kemei KM-1784 es la herramienta ideal para quienes buscan precisión y comodidad en el cuidado personal. Con un potente motor de 7000RPM, esta trimmer permite un corte eficiente y rápido, adaptándose a diferentes estilos y necesidades. Su diseño ergonómico y cabezales removibles facilitan su uso y limpieza, garantizando una experiencia óptima.

Incluye cuchillas de acero de alta calidad y peines guía que permiten ajustar la longitud del corte según tus preferencias. Su batería recargable de 220V asegura un rendimiento prolongado, ideal para viajes o uso diario. Además, es apta para bebés, lo que la convierte en una opción versátil para toda la familia.

La trimmer es completamente inalámbrica, lo que proporciona libertad de movimiento durante su uso. Los cabezales lavables permiten mantener la higiene y el cuidado del producto, asegurando su durabilidad. Con la Patillera Trimmer Kemei, disfrutarás de un acabado profesional en la comodidad de tu hogar.'
where sku = 'LFJ-KM-1784';
update products set active = false, ml_item_id = null where sku = 'MLA1714142711';
update products set active = false, ml_item_id = null where sku = 'MLA3081809124';

-- LFJ-KM-2296 "Clipper inalambrico - 8 posiciones - 3 a 25 mm - Lubricante, cepillo de limpieza, base de carga" <- MLA1714213701 "Cortapelo Clipper + Patillera Trimmer + Accesorios Kemei Plateado"
-- Modelo KM-2296 confirmado en specs, stock exacto (40)
update products set
  images = '["https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA1714213701-1.webp","https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA1714213701-2.jpg","https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA1714213701-3.webp","https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA1714213701-4.jpg","https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA1714213701-5.jpg","https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA1714213701-6.webp"]'::jsonb
where sku = 'LFJ-KM-2296';
update products set active = false, ml_item_id = null where sku = 'MLA1714213701';

-- LFJ-KM-512 "Clipper inalambrico - 3 posiciones - 1.5 a 5 mm - Lubricante, cepillo de limpieza, peine" <- MLA1714244593 "Patillera Trimmer Inalámbrica + 4 Peines Kemei Negro"
-- Modelo KM-512 confirmado en specs, stock exacto (60)
update products set
  images = '["https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA1714244593-1.jpg","https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA1714244593-2.jpg","https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA1714244593-3.webp","https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA1714244593-4.jpg","https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA1714244593-5.webp","https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA1714244593-6.webp"]'::jsonb,
  specs = '[{"label":"Accesorios incluidos","value":"Cargador,Cuchillas de acero,Peines guía"},{"label":"Voltaje de la batería","value":"220V"},{"label":"Marca","value":"Kemei"},{"label":"Color","value":"Negro"},{"label":"Funciones","value":"Cortadora de pelo,Afeitadora"},{"label":"Tipos de cabezales","value":"Ergónomicos,Removibles"},{"label":"Incluye accesorios","value":"Sí"},{"label":"Incluye batería recargable","value":"Sí"},{"label":"Es apta para bebés","value":"Sí"},{"label":"Es apta para viaje","value":"Sí"},{"label":"Es inalámbrica","value":"Sí"},{"label":"Condición del ítem","value":"Nuevo"},{"label":"Color principal","value":"Negro"},{"label":"Modelo","value":"KM-512"},{"label":"Tipo de alimentación","value":"Batería recargable"},{"label":"Voltaje","value":"220V"},{"label":"Con cabezales lavables","value":"Sí"}]'::jsonb,
  description = 'La Patillera Trimmer Inalámbrica Kemei KM-512 es la herramienta ideal para quienes buscan un corte preciso y cómodo. Con su diseño ergonómico y cabezales removibles, permite una experiencia de uso sencilla y efectiva, adaptándose a diferentes estilos y necesidades. 

Incluye cuatro peines guía que facilitan la personalización del largo de corte, asegurando resultados profesionales en la comodidad de tu hogar. Sus cuchillas de acero garantizan un rendimiento duradero y un afeitado suave, apto incluso para los más pequeños de la casa.

La batería recargable proporciona una autonomía excepcional, permitiendo su uso sin cables y haciéndola perfecta para llevar de viaje. Además, sus cabezales lavables aseguran una fácil limpieza, manteniendo la higiene y el cuidado del producto.

Con un voltaje de 220V, esta patillera es versátil y eficiente, ideal para quienes valoran la calidad y la funcionalidad en sus herramientas de cuidado personal. La Kemei KM-512 es la elección perfecta para quienes desean un acabado impecable y una experiencia de uso sin complicaciones.'
where sku = 'LFJ-KM-512';
update products set active = false, ml_item_id = null where sku = 'MLA1714244593';

-- LFJTXD-KM-8557 "Kit clipper + trimmer + shaver inalambrico - Regulador RPM - Lubricante, cepillo de limpieza y base de carga" <- MLA3075432564 "Kit Clipper + Trimmer + Shaver Profesional Premium Kemei Dorado"
-- Modelo KM-8557 confirmado en specs (stock 15 vs 19, se confia en el codigo)
update products set active = false, ml_item_id = null where sku = 'MLA3075432564';

-- LFJ-KM-8526 "Kit clipper + trimmer inalambrico - 7 posiciones - 1 a 9 mm - Lubricante y cepillo de limpieza" <- MLA3081551700 "Kit Clipper + Trimmer + Accesorios 7500rpm Kemei Marrón"
-- Modelo KM-8526 confirmado en specs, stock exacto (20)
update products set
  images = '["https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA3081551700-1.webp","https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA3081551700-2.jpg","https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA3081551700-3.webp","https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA3081551700-4.jpg","https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA3081551700-5.jpg","https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA3081551700-6.webp"]'::jsonb,
  specs = '[{"label":"Accesorios incluidos","value":"Cargador,Cuchillas de acero,Peines guía"},{"label":"Voltaje de la batería","value":"220V"},{"label":"Marca","value":"Kemei"},{"label":"Color","value":"Marrón"},{"label":"Cantidad de peines","value":"4"},{"label":"Funciones","value":"Cortadora de pelo,Afeitadora"},{"label":"Tipos de cabezales","value":"Ergónomicos,Removibles"},{"label":"Incluye accesorios","value":"Sí"},{"label":"Incluye batería recargable","value":"Sí"},{"label":"Es apta para bebés","value":"Sí"},{"label":"Es apta para viaje","value":"Sí"},{"label":"Es inalámbrica","value":"Sí"},{"label":"Condición del ítem","value":"Nuevo"},{"label":"Color principal","value":"Marrón"},{"label":"Modelo","value":"KM-8526"},{"label":"Cantidad de posiciones","value":"4"},{"label":"Tipo de alimentación","value":"Batería recargable"},{"label":"Voltaje","value":"220V"},{"label":"Con cabezales lavables","value":"Sí"}]'::jsonb,
  description = 'Descubre la versatilidad del Clipper y Trimmer Kemei KM-8526, diseñado para ofrecer un corte preciso y cómodo en la comodidad de tu hogar. Con un potente motor de 7500RPM, este dispositivo es ideal tanto para el cuidado del cabello como para el afeitado, adaptándose a las necesidades de toda la familia, incluyendo los más pequeños.

El kit incluye cuchillas de acero de alta calidad y cuatro peines guía, permitiendo múltiples longitudes de corte. Su diseño ergonómico y cabezales removibles facilitan su uso y limpieza, asegurando una experiencia de grooming eficiente y agradable. Además, su batería recargable y su funcionamiento inalámbrico lo hacen perfecto para llevar de viaje.

Con un voltaje de 220V, este producto es apto para cualquier hogar y garantiza un rendimiento óptimo. Los cabezales lavables aseguran una higiene adecuada, mientras que su diseño compacto lo convierte en un aliado ideal para quienes buscan un cuidado personal práctico y efectivo. Mejora tu rutina de cuidado personal con el Clipper y Trimmer Kemei KM-8526, la herramienta que se adapta a tu estilo de vida.'
where sku = 'LFJ-KM-8526';
update products set active = false, ml_item_id = null where sku = 'MLA3081551700';

-- LFJ-KM-8561 "Kit clipper + trimmer inalambrico - 11 posiciones - 1 a 13 mm - Lubricante, cepillo de limpieza y base de carga" <- MLA3081579342 "Kit Clipper + Trimmer + Shaver Con Accesorios 9000rpm Kemei Amarillo"
-- Modelo KM-8561 confirmado en specs, stock exacto (20)
update products set
  images = '["https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA3081579342-1.webp","https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA3081579342-2.jpg","https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA3081579342-3.webp","https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA3081579342-4.jpg","https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA3081579342-5.webp","https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA3081579342-6.webp"]'::jsonb,
  specs = '[{"label":"Accesorios incluidos","value":"Cargador,Cuchillas de acero,Peines guía"},{"label":"Voltaje de la batería","value":"220V"},{"label":"Marca","value":"Kemei"},{"label":"Color","value":"Amarillo"},{"label":"Cantidad de peines","value":"4"},{"label":"Funciones","value":"Cortadora de pelo,Afeitadora"},{"label":"Tipos de cabezales","value":"Ergónomicos,Removibles"},{"label":"Incluye accesorios","value":"Sí"},{"label":"Incluye batería recargable","value":"Sí"},{"label":"Es apta para bebés","value":"Sí"},{"label":"Es apta para viaje","value":"Sí"},{"label":"Es inalámbrica","value":"Sí"},{"label":"Condición del ítem","value":"Nuevo"},{"label":"Color principal","value":"Amarillo"},{"label":"Modelo","value":"KM-8561"},{"label":"Cantidad de posiciones","value":"4"},{"label":"Tipo de alimentación","value":"Batería recargable"},{"label":"Voltaje","value":"220V"},{"label":"Con cabezales lavables","value":"Sí"}]'::jsonb,
  description = 'El Kit Clipper + Trimmer + Shaver de Kemei es la solución ideal para quienes buscan un cuidado personal completo y profesional en la comodidad de su hogar. Con un potente motor de 9000 rpm, este dispositivo garantiza un corte preciso y eficiente, adaptándose a diferentes estilos y necesidades. Su diseño ergonómico y cabezales removibles facilitan su uso y limpieza, asegurando una experiencia agradable y práctica.

Incluye cuatro peines guía que permiten ajustar la longitud del corte, lo que lo hace apto para toda la familia, incluso para bebés. La batería recargable proporciona la libertad de uso inalámbrico, ideal para llevar de viaje o utilizar en cualquier lugar. Además, su voltaje de 220V asegura un rendimiento óptimo en diversas condiciones.

Los accesorios incluidos, como el cargador y las cuchillas de acero, garantizan durabilidad y un mantenimiento sencillo. Con cabezales lavables, este producto se adapta a un estilo de vida moderno y activo, permitiendo un cuidado personal sin complicaciones. La versatilidad de sus funciones como cortadora de pelo y afeitadora lo convierte en una herramienta indispensable para quienes valoran la calidad y la eficiencia en su rutina de cuidado personal.'
where sku = 'LFJ-KM-8561';
update products set active = false, ml_item_id = null where sku = 'MLA3081579342';

-- LFJTXD-KM-8572 "Kit clipper + trimmer + shaver inalambrico - Cepillo de limpieza, base de carga y maletin de almacenamiento" <- MLA3081613838 "Maletín Clipper + Trimmer + Shaver Profesional Premium Kemei Dorado"
-- Modelo KM-8572 confirmado en specs (stock 20 vs 9, se confia en el codigo; "Maletin" del titulo coincide con "maletin de almacenamiento" de la ficha)
update products set
  images = '["https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA3081613838-1.webp","https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA3081613838-2.jpg","https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA3081613838-3.jpg","https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA3081613838-4.jpg","https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA3081613838-5.webp","https://pobfcnezbxrprtymyivi.supabase.co/storage/v1/object/public/product-images/ml-import/MLA3081613838-6.jpg"]'::jsonb,
  specs = '[{"label":"Accesorios incluidos","value":"Cargador,Cuchillas de acero,Peines guía"},{"label":"Voltaje de la batería","value":"220V"},{"label":"Marca","value":"Kemei"},{"label":"Color","value":"Dorado"},{"label":"Cantidad de peines","value":"6"},{"label":"Funciones","value":"Cortadora de pelo,Afeitadora"},{"label":"Tipos de cabezales","value":"Ergónomicos,Removibles"},{"label":"Incluye accesorios","value":"Sí"},{"label":"Incluye batería recargable","value":"Sí"},{"label":"Es apta para bebés","value":"Sí"},{"label":"Es apta para viaje","value":"Sí"},{"label":"Es inalámbrica","value":"Sí"},{"label":"Condición del ítem","value":"Nuevo"},{"label":"Color principal","value":"Dorado"},{"label":"Modelo","value":"KM-8572"},{"label":"Cantidad de posiciones","value":"5"},{"label":"Tipo de alimentación","value":"Batería recargable"},{"label":"Voltaje","value":"220V"},{"label":"Con cabezales lavables","value":"Sí"}]'::jsonb
where sku = 'LFJTXD-KM-8572';
update products set active = false, ml_item_id = null where sku = 'MLA3081613838';

